import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import Footer from "./_components/Footer/Footer";
import {Toaster} from "react-hot-toast"
import Nextaouthprovider from "./Provider/nextaouthprovider";
import Providers from "./Provider/react-quary-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Nextaouthprovider>
            <Toaster />
            <Navbar />
            <div className="container mx-auto max-w-5/6">{children}</div>
            <Footer />
          </Nextaouthprovider>
        </Providers>
      </body>
    </html>
  );
}
